fidals/shopelectro

- etc/se-backup-restore.sh
- shopelectro/management/commands/_update_catalog/update_tags.py
- shopelectro/management/commands/_update_catalog/utils.py
- shopelectro/tests/tests_commands.py
Closes #232 
Убрал в 1С-выгрузке снос тегов, что были в базе до выгрузки, но не были в файлах 1С
> 232  Remove extra tags dropping after 1C export

- docker/Makefile
- docker/docker-compose-production.yml
- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/settings/base.py
Это нужно для того, чтобы теги, добавленные через Админку, не затирались при 1С-экспорте
> 232  Don't rewrite product.tags in export, but merge them

- docker/docker-compose.yml
- requirements.txt
- shopelectro/settings/base.py
- shopelectro/tests/tests_views.py
Closes #394 
I'll create stb clone after this code approving
> #394  Redirects dep. stb2

- shopelectro/admin.py
- shopelectro/views/service.py
And change order list fields set at admin panel
Closes #543
> #543  Add log to ya aviso view. 

- .coafile
- shopelectro/context.py
- shopelectro/management/commands/_update_catalog/update_tags.py
- shopelectro/models.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
It's the start of splitting CatalogPage's monolith code
Closes #550 
Closes #548
> #550  Split TaggedCategoryPage class

- requirements.txt
- shopelectro/context.py
- shopelectro/models.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
Closes https://github.com/fidals/refarm-site/issues/168
> rf#168  Prepare context module for moving to refarm

- requirements.txt
> #463  Pin celery version to `4.2.0` to fix celery deps error

- requirements.txt
- shopelectro/management/commands/excel.py
- shopelectro/management/commands/price.py
- shopelectro/management/commands/test_db.py
- shopelectro/models.py
- shopelectro/sitemaps.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_admin.py
- shopelectro/tests/tests_selenium_mobile.py
- shopelectro/tests/tests_templatetags.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- shopelectro/views/search.py
- templates/catalog/category_products.html
- templates/catalog/product.html
- templates/index/featured.html
- templates/layout/tile_products.html
Closes https://github.com/fidals/refarm-site/pull/196
Closes #575 
Depends on https://github.com/fidals/refarm-site/pull/196
> rf#182  Move prepare products to context

- docker/docker-compose-production.yml
- docker/docker-compose.yml
- etc/gunicorn.py
- etc/nginx/default.conf
- requirements.txt
- shopelectro/models.py
> #603  Create timeouts for cache warmup

- requirements.txt
- shopelectro/context.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/catalog/category_products.html
- templates/layout/tile_products.html
... and customize images context
Depends on https://github.com/fidals/refarm-site/pull/206
https://github.com/fidals/refarm-site/issues/197
https://github.com/fidals/refarm-site/issues/198
> rf#197  Rm prepare_data from context

- shopelectro/context_processors.py
- shopelectro/settings/base.py
- templates/ecommerce/order/email.html
- templates/ecommerce/order/success.html
- templates/ecommerce/yandex_feedback.html
- templates/layout/footer.html
- templates/layout/header.html
- templates/layout/metadata.html
> Remove an order's phone from the success page

- front/less/pages/order.less
- templates/ecommerce/order/success.html
> #636 content of a success order page

- .drone.yml
- docker/docker-compose.yml
- docker/wait-for.sh
> #624 test-docker-compose ci pipeline

- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/models.py
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_views.py
- shopelectro/views/search.py
Closes #655
Closes #662
Closes #667
Closes #669
> Set of minor cleanup fixes

- shopelectro/models.py
- shopelectro/selenium/conditions.py
- shopelectro/selenium/driver.py
- shopelectro/selenium/elements/__init__.py
- shopelectro/selenium/elements/button.py
- shopelectro/selenium/elements/input.py
- shopelectro/selenium/elements/product_card.py
- shopelectro/selenium/pages/__init__.py
- shopelectro/selenium/pages/category.py
- shopelectro/selenium/pages/order.py
- shopelectro/selenium/pages/page.py
- shopelectro/settings/base.py
- shopelectro/tasks.py
- shopelectro/tests/tests_selenium.py
- templates/ecommerce/order/email.html
- templates/ecommerce/yandex_order_email.html
> #690 #498 #497 Make the check_purchase work

- front/js/shared/tracking.es6
- templates/layout/google_tag_manager.html
> #759 google ecommerce

- shopelectro/tests/tests_js_analytics.py
> #785 test yandex ecommerce

- requirements.txt
Update it to fix ga (google analytics) tracker problem:
https://sentry.fidals.com/fidals/shopelectro-front/issues/267/?query=is:unresolved
> #fix  Grade refarm to 0.5.7

- front/less/pages/catalog.less
- requirements.txt
- shopelectro/tests/tests_selenium_admin.py
- shopelectro/urls.py
- shopelectro/views/catalog.py
- templates/catalog/catalog.html
> #822  Create categories matrix page

- front/js/components/order.es6
- front/less/common/variables.less
- front/less/pages/order.less
- templates/ecommerce/order/table_form.html
> #816 Add privacy policy agreement to order page.

- docker/Makefile
- requirements.txt
- shopelectro/admin.py
- shopelectro/tests/tests_selenium_admin.py
> #835 admin price filter

- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
Closes #836 
Didn't test block items limiting. The test should be too complex, for a such minor limiting feature
> #836  Test categories matrix sorting

- shopelectro/tests/tests_models.py
- shopelectro/tests/tests_views.py
> #887  Exclude not active crumbs siblings

- shopelectro/tests/tests_js_analytics.py
- shopelectro/tests/tests_selenium.py
> #808 review fixes

- shopelectro/selenium/__init__.py
- shopelectro/selenium/analytics_goals.py
- shopelectro/selenium/driver.py
- shopelectro/tests/tests_js_analytics.py
- shopelectro/tests/tests_selenium.py
> #929 ecommerce goals for tests

- .gitignore
- shopelectro/selenium/analytics_goals.py
- shopelectro/selenium/elements/__init__.py
- shopelectro/selenium/elements/cart.py
- shopelectro/selenium/elements/positions.py
- shopelectro/selenium/elements/product.py
- shopelectro/selenium/pages/category.py
- shopelectro/selenium/pages/order.py
- shopelectro/selenium/pages/product.py
- shopelectro/tests/tests_js_analytics.py
> #938 #939 test order page remove goal

- docker/docker-compose-production.yml
Current backup system takes too much disk space on serv.
Our files and DB are not changed too frequently. So it should do incremental backups instead of the full ones every time.
Mentioned incremental backups idea at the https://github.com/fidals/stroyprombeton/issues/188
We'll implement them with this task or it's subtask
> #fix  Rm backup docker service

- .editorconfig
- docker/Makefile
> #953 Create makefile recipes for celery stop/start

- front/js/components/orderCall.es6
- front/js/components/product.es6
- front/js/shared/mediator.es6
- front/js/shared/tracking.es6
- templates/layout/google_tag_manager.html
It's untested and may be unstable
Closes #977
> #977  Send user's phone to CarrotQuest service
