- README.md
- shopelectro/settings/base.py
- shopelectro/settings/local.py
- shopelectro/views.py
- templates/shopelectro/main.html
Create reusable breadcrumbs with microdata
> [ 706 ] Rebase commit

- requirements.txt
> Change repo req link protocols from git to https

- docker/Dockerfile
- shopelectro/settings/base.py
> FF Fix x-frame-options option

- .dockerignore
- docker/.env.dist
- manage.py
- shopelectro/settings/base.py
- shopelectro/settings/local.py.dist
- shopelectro/views/ecommerce.py
816  Repair STB docker image building
816  Just copy config from SE
> [816] With STB release refactor

- shopelectro/management/commands/catalog.py
Fixed this bug:
https://trello.com/c/RPxZvzmg/187-se-fix-yml-feed
> Fix market description

- shopelectro/settings/prod.py
* https://trello.com/c/PTdo5zBi/240-se-admin-products-media-bug
> Removed json serializer from sorl thumbnails cache settings

- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
* https://trello.com/c/9BbCywDe/242-se-hide-orphan-prods
> Hide orphan prods

- shopelectro/management/commands/price.py
- shopelectro/models.py
- templates/prices/price.yml
https://trello.com/c/z2ajzh4P/248-se-yml
https://trello.com/c/HYxnN2Iq/249-se-yml
> Yml prices features

- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/management/commands/_update_catalog/utils.py
- shopelectro/management/commands/update_catalog.py
- shopelectro/management/commands/update_meta_tags.py
- shopelectro/tasks.py
* https://trello.com/c/ajP0Ased/259-se-create-import-s-error-message
> Catalog update task fixes

- front/js/components/product.es6
- front/less/common/variables.less
- front/less/pages/product.less
- shopelectro/management/commands/update_meta_tags.py
- shopelectro/models.py
- shopelectro/views/catalog.py
- templates/catalog/product.html
- templates/catalog/product_feedback.html
- templates/layout/header.html
https://trello.com/c/Np1udBie/246-se
- Добавлена таблица хараеткристик товара на ProductPage
- Добавлено сворачивание длинных описаний товаров на тех же ProductPage
- Исправлен баг с невидимыми названиями категорий в разворачиваемом списке "Каталог товаров" на мобильной версии.
- Исправлено множественное число слова "feedback" по коду
- ~~Исправлено дублирование СЕО-текста в описаниях категорий~~
> Product page features

- templates/robots.txt
https://trello.com/c/xG4rNf5D/263-se-robots-txt-update
> Custom robots.txt template

- templates/catalog/product.html
- templates/layout/header.html
https://trello.com/c/eQTfBnMa/264-se
> Fix bug with subcategories (mobile navigation)

- front/js/components/autocomplete.es6
- front/js/components/mobileMenu.es6
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_mobile.py
- templates/ecommerce/header_cart.html
> Cart amounts

- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/layout/base.html
- templates/layout/metadata.html
> 172  Resolve canonical url on CategoryPage

- shopelectro/views/catalog.py
- templates/layout/base.html
- templates/layout/metadata.html
Seo guys wished to skip canonical urls on CategoryPage with selected tags
> fix  Skip canonical url for category tags page

- .travis.yml
- docker/coala/Dockerfile
- docker/docker-compose.yml
> PDD tasks validation

- doc/source/index.rst
- docker/docker-compose.yml
Задокументил ошибку по npm-images
> fix Doc npm images bug

- shopelectro/views/catalog.py
> [#195] Add raw tags to page template context

- shopelectro/tests/tests_views.py
- templates/catalog/product.html
> Implemented product property linking

- shopelectro/tests/tests_views.py
- templates/catalog/category_product_image.html
- templates/catalog/product_images.html
- templates/index/product_thumbnail.html
Related to https://github.com/fidals/refarm-site/issues/87
> Change sorl-thumbnail output format to PNG

- shopelectro/admin.py
- shopelectro/settings/base.py
- shopelectro/urls.py
> Add category autocomplete to admin product page inline

- shopelectro/sitemaps.py
- shopelectro/urls.py
> Add category with tags to sitemap

- .drone.yml
Первая часть #177, посмотреть как всё получается в итоге можно тут: https://ci.fidals.com/fidals/shopelectro/122 
В этом PR нет этапа деплоя, т.к. с окончательным вариатом деплоя пока-что не определились
> Implemented docker build & push pipelines

- front/less/pages/product.less
- templates/catalog/category.html
https://css-tricks.com/almanac/properties/o/overflow-anchor/
Closes #194
> Fix issues with scrolling after click on load more products button

- docker/Makefile
this stb's pr is the same:
https://github.com/fidals/stroyprombeton/pull/129
> fix  Sync se and stb makefiles

- docker/.env.dist
- docker/docker-compose.yml
- shopelectro/tests/tests_views.py
- templates/pages/page_h1.html
- templates/search/results.html
Depends on https://github.com/fidals/refarm-site/pull/104
- Переработал структуру шаблонов и темплейт-тегов для search
- Подключил поиск к новому интерфейсу рефармового SearchView
> rf#103  Adapt search to new refarm SearchView CBV arch

- docker/Makefile
> Run backup before deploy recipe

- shopelectro/tests/tests_selenium.py
- templates/robots.txt
> #238 Update robots.txt

- front/js/shared/configs.es6
- shopelectro/tests/tests_selenium_mobile.py
> #239 mobile search submit button

- README.md
- docker/Makefile
- docker/docker-compose.yml
> #229  Document local env building

- templates/catalog/product_delivery.html
> #251 Update a delivery price for product.

- templates/prices/price.yml
> #257 Comment description tags in price files.

- .drone.yml
- templates/robots.txt
> #254  Fix robots.txt template

- shopelectro/models.py
- shopelectro/sitemaps.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
> Refactor Tag.serialize_* methods (close #221)

- .drone.yml
- README.md
- docker/Makefile
- docker/docker-compose.yml
- docker/node/Dockerfile
Closes #248 
- Fix drone. Improve makefile
- Drone now builds and pushes fidals/se-nodejs image
- Move npm-install from dc.yml to Dockerfile
> #248  Move npm-install from dc.yml to Dockerfile

- front/less/common/common.less
- front/less/pages/main.less
> Replaced New Year background pattern

- front/less/pages/product.less
- shopelectro/admin.py
- templates/catalog/product.html
> #263 Enable a vendor code for the product page of mobile version

- shopelectro/tests/tests_views.py
- templates/catalog/product.html
> #288 Fix a link of product page to the schema.org

- templates/layout/header.html
> #289 Update a phone number in header.

- front/js/components/index.es6
- front/js/components/product.es6
- front/js/shared/helpers.es6
- front/less/common/common.less
- front/less/pages/product.less
- gulpfile.babel.js
- templates/catalog/product.html
- templates/index/index.html
- templates/layout/toggle_content.html
> #281 Add a display_seo_text to the index page.

- shopelectro/admin.py
> #284 Add orders list to admin page

- shopelectro/admin.py
> #282 Enable ability to adding a new category page

- docker/docker-compose.yml
- shopelectro/tests/helpers.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_admin.py
- shopelectro/tests/tests_selenium_mobile.py
> #244 Add explicit wait of element to fix test

- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/settings/base.py
> #309 Reduce retail prices. Create docs for PRICE_REDUCER const.

- docker/docker-compose.yml
- docker/env_files/app.dist
- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/management/commands/_update_catalog/utils.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_commands.py
> #319  Multiply prices on coefficient

- README.md
- docker/Makefile
> #313  Create prepare-deploy rule. Recreate nginx container during deploy

- templates/404.html
Closes #225 
This PR is copy of https://github.com/fidals/shopelectro/pull/264 authored by @Filarius
> #225  Repeat 404 button fix

- shopelectro/settings/base.py
- shopelectro/tests/tests_views.py
- shopelectro/urls.py
- shopelectro/views/catalog.py
- templates/catalog/category.html
- templates/catalog/category_products.html
> #302 catalog pagination

- .drone.yml
- front/js/components/autocomplete.es6
- front/js/components/category.es6
- front/js/components/headerCart.es6
- front/js/components/order.es6
- front/js/components/orderCall.es6
- front/js/components/product.es6
- front/js/shared/configs.es6
- front/js/shared/helpers.es6
- front/js/shared/yandex.es6
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
Closes #341 
I am going to enable push hook for drone to ensure build starting when we merge changes to master branch
> #341 Resurrect coala eslint.

- shopelectro/tests/tests_views.py
@artemiy312 , look at this fix plz
> #fix  Fix pdd puzzle

- .drone.yml
#347 
Seems it works :) Before closing the issue, let's try to merge PR and check master build
> #347 Fix doubled ci execution

- docker/docker-compose.yml
Closes https://github.com/fidals/shopelectro/issues/331
> Не используем debug образ selenium

- requirements.txt
- shopelectro/settings/base.py
Closes https://github.com/fidals/shopelectro/issues/337
> Не используем dj_database_url

- shopelectro/tests/helpers.py
> #371  Increase tests timeouts

- docker/images/node/Dockerfile
- shopelectro/tests/tests_views.py
Closes #361
I'll repeat it on STB in https://github.com/fidals/stroyprombeton/issues/203
> #361  Fix `npm install gulp-imagemin` problem

- templates/robots.txt
> #367  Fix robots.txt bug

- .editorconfig
> rf#112  Add .editorconfig

- shopelectro/settings/base.py
- shopelectro/settings/local.py.dist
- shopelectro/tests/helpers.py
https://github.com/fidals/refarm-site/issues/92
> rf#92  Enable connection pool

- shopelectro/tests/tests_views.py
> Split catalog page test class into smaller parts

- requirements.txt
- shopelectro/settings/base.py
- shopelectro/settings/local.py.dist
- shopelectro/sitemaps.py
- shopelectro/urls.py
Related to #343, closes #375, related to fidals/refarm-site#136
> #343 Bump a version of RF. Use custom_page_url and RobotsView.

- .drone.yml
- docker/Makefile
- docker/docker-compose.yml
And renew Makefile for lint for a little
Closes #380 
Closes #383
> #380  Rm redundant lint services deps

- .gitignore
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/catalog/category.html
- templates/catalog/category_pagination.html
- templates/catalog/category_products.html
- templates/layout/base.html
- templates/layout/metadata.html
The PR does not implement some requirements(2 pagination buttons instead of 5), because we are going to hide pagination buttons from users, @duker33 is it okay?
Closes #340
> #340 Create pagination buttons and canonical links.

- docker/env_files/app.dist
https://github.com/fidals/stroyprombeton/issues/238
> stb#238  Define COMPOSE_PROJECT_NAME

- docker/docker-compose-production.yml
> stb#233  Forward local.py config according to prod

- gulpfile.babel.js
- package.json
> Заменила babel-preset-es2015 на babel-preset-env

- docker/images/python/Dockerfile.prod
> Add checks for python production Dockerfile

- .drone.yml
- docker/Makefile
- docker/docker-compose-build.yml
- docker/docker-compose.yml
- docker/drone_env/.env
- docker/drone_env/paths
- docker/env_files/paths.dist
- docker/images/node/Dockerfile
- gulpfile.babel.js
- shopelectro/settings/base.py
Closes fidals/stroyprombeton#245 and closes fidals/stroyprombeton#246
> fidals/stroyprombeton#245 fidals/stroyprombeton#246  Remove the app service's depedency from a nodejs service.

- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_templatetags.py
> #413 Fix presence of navigation links.

- shopelectro/urls.py
> #418  Disable slash auto appending for robots redirects

- shopelectro/settings/base.py
- shopelectro/tests/helpers.py
> Move test timeouts to env vars

- shopelectro/tests/tests_views.py
> #417  Prove failed /robots.txt with test

- shopelectro/urls.py
> #420 Fix RobotsView queryset

- docker/docker-compose-production.yml
> Fix prices auto-update

- docker/docker-compose-production.yml
https://github.com/fidals/stroyprombeton/issues/260
> stb#260  Rm redundant services ports forwarding

- .drone.yml
- shopelectro/settings/base.py
https://github.com/fidals/refarm-site/issues/132
> rf#132  Rm redundant volumes

- docker/Makefile
- docker/docker-compose.yml
- docker/images/node/Dockerfile
- shopelectro/settings/base.py
Closes https://github.com/fidals/stroyprombeton/issues/257
Closes https://github.com/fidals/stroyprombeton/issues/258
> se#258  Fix gulp build. Fix built asserts dir in app's config

- shopelectro/tests/tests_views.py
https://github.com/fidals/refarm-site/issues/151
> rf#151  Move redirect tests to refarm_redirect app

- .drone.yml
- shopelectro/exception.py
- shopelectro/management/commands/_update_catalog/utils.py
- shopelectro/tests/tests_commands.py
> #441  Skip update_catalog tests while 1C is not fixed

- front/js/components/order.es6
- front/js/components/product.es6
- front/js/shared/yandex.es6
- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/management/commands/excel.py
- shopelectro/management/commands/price.py
- shopelectro/models.py
- shopelectro/views/catalog.py
- shopelectro/views/search.py
Closes #273 
Prevent products removing during 1C update
> #273 Do not remove products

- requirements.txt
Closes #435
Without review, only dep version fix
> #435  Fix h1 length with new refarm version

- .drone.yml
- docker/docker-compose.yml
- docker/drone_env/paths
> #352  Rm npm step

- front/js/components/order.es6
- front/js/components/product.es6
> #439 Fix reaching of Ya's buying goals

- shopelectro/management/commands/_update_catalog/utils.py
- shopelectro/tests/tests_commands.py
Signed-off-by: duker33 <duker33@gmail.com>
> #fix  Return 1C tests

- .drone.yml
- docker/docker-compose.yml
- docker/images/python/Dockerfile.prod
- gulpfile.babel.js
- shopelectro/settings/base.py
- shopelectro/tests/tests_selenium.py
Closes #454 
https://github.com/fidals/stroyprombeton/issues/272
> #454, stb#272. Repeat stb front dir. Resurrect test

- front/js/components/headerCart.es6
- front/js/components/order.es6
- front/js/components/product.es6
- front/js/shared/yandex.es6
- templates/ecommerce/order/table_form.html
> Implement rest of js tracking actions

- requirements.txt
- shopelectro/settings/base.py
- shopelectro/settings/drone.py
- shopelectro/settings/local.py.dist
> Pin celery version. Move SELENIUM_* variables to local.py/drone.py

- .drone.yml
- docker/docker-compose.yml
- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/catalog/product_404.html
> #444  Render siblings on 404 product page

- .drone.yml
- docker/docker-compose-build.yml
- docker/docker-compose.yml
- docker/images/node/Dockerfile
- docker/images/python/Dockerfile.prod
> #448 Use python image in drone

- .gitignore
- shopelectro/views/catalog.py
- templates/404.html
- templates/catalog/product_404.html
- templates/index/index.html
- templates/layout/tile_products.html
> #470 Create styles for 404 related products. 

- .coafile
- shopelectro/management/commands/price.py
- shopelectro/tests/tests_commands.py
> #478  Fix not excluded from price category bug

- shopelectro/management/commands/price.py
- shopelectro/models.py
- shopelectro/views/catalog.py
- shopelectro/views/search.py
Closes #445 
Closes #480 
Closes #484
> #445  Create and use ProductActiveManager

- front/js/components/order.es6
Closes #487 
Yandex form could not be rendered in time after requesting order data to backend
> #487  Fix redirection to Ya.Kassa

- front/js/shared/yandex.es6
- gulpfile.babel.js
- package.json
- templates/layout/google_tag_manager.html
> Add ga(...) as reserved word for uglify

- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_models.py
> Create test for creation of deactivated product

- docker/env_files/paths.dist
- front/js/components/order.es6
- shopelectro/settings/base.py
- shopelectro/tests/tests_selenium.py
Closes #489 
- Test ya kassa form
- Describe special bug with ya kassa
Special bug is because of modifing cart directly on order page
> #489  Test yandex kassa form selection

- requirements.txt
> #433 Pin django-redis to 4.8.0 version

- .drone.yml
Closes fidals/stroyprombeton#263
> stb#263 Add secrets: option to .drone.yml

- .coafile
- front/js/components/headerCart.es6
- front/js/components/order.es6
- front/js/shared/yandex.es6
> #485  Apply js linter rules

- docker/docker-compose.yml
- front/js/components/order.es6
- front/less/common/variables.less
- shopelectro/models.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/catalog/product.html
> #388  Product page siblings

- front/less/vendors/bootstrap/dropdowns.less
- front/less/vendors/bootstrap/variables.less
- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/templatetags/se_extras.py
> #510  Rm or move to pdd all TODO's

- front/js/components/category.es6
- shopelectro/tests/tests_views.py
- templates/catalog/category_pagination.html
> Hide a catalog's pagination buttons

- .gitignore
- shopelectro/tests/tests_views.py
> #398  Create problem for tags in different groups

- front/js/components/category.es6
- front/js/components/order.es6
- front/js/components/product.es6
- front/js/shared/tracking.es6
- shopelectro/views/catalog.py
- templates/catalog/category.html
- templates/catalog/category_products.html
- templates/catalog/product.html
- templates/ecommerce/order/table_form.html
Closes #504 
Implemented [features](https://github.com/fidals/shopelectro/issues/504#issuecomment-412660540)
> #504  Extend sending info about products to YA and GA systems

- front/js/components/order.es6
- front/js/shared/tracking.es6
- shopelectro/tests/tests_selenium.py
> #496 Fix ya.kassa payment process

- shopelectro/models.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_models.py
- shopelectro/tests/tests_views.py
- shopelectro/urls.py
> #522  Make tag slugs autounique

- front/js/components/order.es6
- front/js/components/product.es6
- front/js/shared/configs.es6
- front/js/shared/tracking.es6
- shopelectro/views/ecommerce.py
- templates/ecommerce/order/success.html
> #524 jsecommerce purchase

- shopelectro/management/commands/price.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_commands.py
> #533  Set lower bound for gm.yml offers

- requirements.txt
- shopelectro/management/commands/price.py
- shopelectro/settings/base.py
- shopelectro/tests/helpers.py
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_models.py
- shopelectro/tests/tests_views.py
> #535  #547  Move utm filter processing to separated class

- requirements.txt
- shopelectro/models.py
> #506 Move Product.get_siblings implementation to RF

- shopelectro/settings/base.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/catalog/category.html
- templates/catalog/category_pagination.html
> #539 pagination buttons

- front/js/components/category.es6
- front/js/components/headerCart.es6
- front/js/components/order.es6
- front/js/components/product.es6
- front/js/shared/tracking.es6
- templates/catalog/category_products.html
- templates/ecommerce/header_cart.html
- templates/ecommerce/order/table_form.html
> #526 Update HTML data format

- requirements.txt
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- Return 404 for non-existing tags
- Fix error with unstable tag slug
Closes #554 
Closes #558
> #554  Fix tag slug behaviour

- shopelectro/tests/tests_views.py
> #555 Create test_numbered_pagination_links

- shopelectro/tests/tests_views.py
It will fix my mistake: https://ci.fidals.com/fidals/shopelectro/816/9
> Fix the CatalogPagination.test_pagination_canonical test

- docker/docker-compose-production.yml
- requirements.txt
> #561 Bump refarm version

- docker/docker-compose.yml
- docker/drone_env/.env
- docker/images/python/Dockerfile.dev
- requirements.txt
> #570 Migrate python to 3.7

- shopelectro/management/commands/price.py
- shopelectro/tests/tests_commands.py
- templates/prices/price.yml
> #565 add vendor to yml

- front/js/components/order.es6
- shopelectro/views/ecommerce.py
- templates/ecommerce/order/table_form.html
> #581 Get id of order's fields from backend to frontend

- .drone.yml
> #587 Fix a syntax error in docker-up pipe 

- .drone.yml
- shopelectro/management/commands/excel.py
> #591 Fix env substitution in docker-compose.yml for docker-rm 

- front/less/common/common.less
- front/less/pages/main.less
> #609  Apply new year styles

- etc/redis/redis.conf
- requirements.txt
- shopelectro/settings/base.py
> #606  Fix and enable caching mech

- shopelectro/models.py
> #542  Refactor import styles

- requirements.txt
- shopelectro/settings/base.py
- shopelectro/views/catalog.py
> #603  Fix performance issues for category and index pages

- shopelectro/views/catalog.py
- templates/layout/header.html
> #621, #607  Fix product page performance and cache menu

- .drone.yml
- docker/drone_env/credentials
- docker/env_files/credentials.dist
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_selenium.py
- shopelectro/views/catalog.py
> #fix  Load more button had been failed

- requirements.txt
- shopelectro/tests/tests_selenium.py
- shopelectro/views/catalog.py
Related to fidals/refarm-site#208
> rf#208 Remove an excess argument from get_category_descendants

- .drone.yml
- shopelectro/settings/base.py
- shopelectro/tests/runner.py
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_models.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_admin.py
- shopelectro/tests/tests_selenium_mobile.py
- shopelectro/tests/tests_templatetags.py
- shopelectro/tests/tests_views.py
- shopelectro/tests/tests_wholesale.py
> #639 divide tests

- shopelectro/tests/tests_views.py
> #648  Create test for failed db_template render

- templates/index/index.html
> #658  Fix h1 for new-year stuff

- requirements.txt
- shopelectro/management/commands/excel.py
- shopelectro/management/commands/price.py
- shopelectro/management/commands/test_db.py
- shopelectro/models.py
- shopelectro/sitemaps.py
- shopelectro/tests/tests_commands.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_admin.py
- shopelectro/tests/tests_templatetags.py
- shopelectro/tests/tests_views.py
- shopelectro/views/search.py
Closes #612 
Huge amount of autochange
> #612  Fix inheritance

- shopelectro/management/commands/price.py
- shopelectro/tests/tests_commands.py
> #661  Change utm for YaMarket's price.yml

- .coafile
- shopelectro/management/commands/_update_catalog/update_products.py
- shopelectro/tests/tests_commands.py
> #656  Prove update_db pages consistency problems with test

- requirements.txt
https://github.com/fidals/stroyprombeton/issues/314
> stb#381  Grade refarm version to 0.4.22

- shopelectro/tests/tests_selenium.py
- shopelectro/views/ecommerce.py
- shopelectro/views/service.py
> #671 phone in order mail

- docker/docker-compose.yml
- requirements.txt
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_views.py
- shopelectro/urls.py
- shopelectro/views/catalog.py
- templates/catalog/category_pagination.html
- templates/catalog/category_products.html
- templates/layout/tile_products.html
https://github.com/fidals/stroyprombeton/issues/314
https://github.com/fidals/stroyprombeton/issues/336
Closes #637
> Set of minor fixes

- shopelectro/tests/tests_views.py
https://github.com/fidals/stroyprombeton/issues/340
> stb#340  Refactor test name

- docker/docker-compose.yml
- requirements.txt
- shopelectro/settings/local.py.dist
- shopelectro/sitemaps.py
- shopelectro/tests/tests_selenium.py
https://github.com/fidals/refarm-site/issues/230
> rf#230  Refactor const name. CustomPage.ROUTE is the new one

- shopelectro/models.py
- shopelectro/tests/tests_selenium.py
> #494  Unskip working `test_cart_page_open`

- shopelectro/tests/tests_commands.py
> #679  Create Prices class for tests

- docker/docker-compose.yml
- requirements.txt
- shopelectro/context.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/catalog/category.html
- templates/catalog/category_pagination.html
- templates/catalog/category_products.html
- templates/layout/base.html
- templates/layout/metadata.html
> #683 new context

- requirements.txt
- shopelectro/context.py
- shopelectro/views/catalog.py
- templates/catalog/category.html
> #701 page context

- docker/images/python/Dockerfile.dev
- requirements.txt
- shopelectro/tests/tests_views.py
> #651 fix segfault issue

- shopelectro/settings/base.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
- templates/index/tile.html
> 711_fix_stale_links

- requirements.txt
- shopelectro/management/commands/price.py
- shopelectro/sitemaps.py
- shopelectro/tests/tests_views.py
https://github.com/fidals/refarm-site/issues/253
> rf#253  Use new product queryset methods

- shopelectro/management/commands/price.py
- shopelectro/tests/tests_commands.py
> 715_split_context

- shopelectro/context.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_views.py
- templates/layout/base.html
- templates/layout/metadata.html
> 718_add_canonical

- docker/docker-compose-production.yml
- shopelectro/celery.py
- shopelectro/selenium/driver.py
- shopelectro/tasks.py
> #712 #724 schedule check purchase

- docker/docker-compose.yml
- docker/images/python/Dockerfile.dev
- shopelectro/celery.py
> #707 Rollback python to 3.6

- requirements.txt
Related to fidals/refarm-site#264
> rf#264 Bump django

- .coafile
- requirements.txt
- shopelectro/cart.py
- shopelectro/context.py
- shopelectro/exception.py
- shopelectro/request_data.py
- shopelectro/settings/base.py
- shopelectro/sitemaps.py
- shopelectro/tests/tests_views.py
- shopelectro/tests/tests_wholesale.py
- shopelectro/urls.py
- shopelectro/views/catalog.py
- shopelectro/views/ecommerce.py
Closes #699
Closes #723
- Move request processing from views to separated module (#723)
- Move context processing from views to separated module (#699)
> #699 #723  Category context, Category request data

- requirements.txt
- shopelectro/context.py
- shopelectro/tests/tests_selenium.py
- templates/catalog/catalog.html
- templates/catalog/category.html
- templates/catalog/category_products.html
- templates/catalog/product.html
- templates/index/index.html
- templates/layout/header.html
- templates/layout/metadata.html
- templates/layout/tile_products.html
- templates/pages/page.html
- templates/pages/pages.html
- templates/pages/sitemap.html
- templates/prices/price.yml
- templates/search/results.html
> #728  Improve page display interface

- requirements.txt
- shopelectro/settings/base.py
> #734 Integrate sentry

- shopelectro/tests/tests_views.py
- templates/catalog/product.html
Closes #739
The real problem was at the containers. See the related task comments for details
> #739  Fix page invocation in templates

- templates/catalog/product.html
Closes #739
We'll provide clear solution at #742
> #739  Fix display fields for product page

- requirements.txt
- shopelectro/tests/tests_models.py
- shopelectro/tests/tests_views.py
- templates/catalog/product.html
- templates/pages/sitemap.html
> #739  Grade refarm dep to fix diplay h1 bug

- requirements.txt
- shopelectro/tests/tests_views.py
> #747  Grade refarm dep to fix doubled groups issue

- docker/images/python/Dockerfile.dev
- requirements.txt
- shopelectro/management/commands/price.py
- shopelectro/settings/base.py
- shopelectro/sitemaps.py
- shopelectro/tests/tests_views.py
- shopelectro/views/catalog.py
Closes [fidals/refarm-site#282](https://github.com/fidals/refarm-site/issues/282) closes #462
> rf#282 Use order_by_alphanumeric

- docker/Makefile
- docker/images/python/Dockerfile.dev
- shopelectro/admin.py
> #752 resend order email

- docker/Makefile
- requirements.txt
- shopelectro/migrations/0033_index_tag_alphanumeric_name.py
- shopelectro/migrations/0034_index_tag_alphanumeric_name_2.py
- shopelectro/models.py
- shopelectro/settings/base.py
- shopelectro/sitemaps.py
Depends on [fidals/refarm-site#299](https://github.com/fidals/refarm-site/pull/299)
> #fixes Bunch of cleanup fixes

- shopelectro/management/commands/price.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_commands.py
- templates/prices/price.yml
> #769  Ignore price entities with config

- docker/docker-compose.yml
- requirements.txt
- shopelectro/context.py
- shopelectro/management/commands/price.py
- shopelectro/request_data.py
- shopelectro/views/catalog.py
Depends on https://github.com/fidals/refarm-site/pull/307
> #set  of minor fixes related to stb

- front/js/components/order.es6
- shopelectro/tests/tests_selenium.py
> #766 Move publishing of onOrderSend before submit.

- shopelectro/tests/tests_views.py
- shopelectro/urls.py
> #776 Disable http cache for OrderPage

- docker/docker-compose.yml
Proposal to uncomment refarm volumes.
They are always enabled as for me. And this fact creates a lot of cvs noise
> #fix  uncomment refarm volumes forever

- shopelectro/tests/tests_selenium.py
> #783 test inconsistent cache issue

- .drone.yml
- front/js/shared/tracking.es6
- requirements.txt
- shopelectro/tests/tests_js_analytics.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_views.py
Closes #761 
Closes #791 
Closes #780
> #761 #791 #780 Create gaLoader and move it to RF

- front/js/components/headerCart.es6
- shopelectro/tests/tests_selenium.py
- templates/layout/header.html
> #794 lazy cart

- docker/Makefile
- shopelectro/management/commands/test_db.py
> #404  Create make rule for temp db

- requirements.txt
- shopelectro/models.py
> #805  Use the new catalog classes arch

- shopelectro/tests/tests_js_analytics.py
https://github.com/fidals/refarm-site/pull/321
> #fix  Skip failed GA test

- front/js/shared/tracking.es6
- shopelectro/tests/tests_js_analytics.py
- templates/layout/google_tag_manager.html
> #812 Fix tests of google analytics

- docker/docker-compose.yml
- front/less/pages/category.less
- shopelectro/management/commands/excel.py
- shopelectro/sitemaps.py
- shopelectro/tests/tests_views.py
- templates/catalog/category_products.html
- templates/layout/footer.html
- templates/layout/header.html
https://github.com/fidals/refarm-site/issues/323
Closes #815
Closes #820
Closes #821
Closes #825
Closes #824
> Set of minor seo fixes

- front/js/components/categoryFilters.es6
- shopelectro/settings/base.py
- shopelectro/tests/tests_selenium_mobile.py
- templates/catalog/category.html
- templates/catalog/category_tags.html
> #826 #830 collapse mobile tags

- front/less/common/common.less
- shopelectro/settings/base.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_templatetags.py
- templates/layout/header.html
> #823 header categories

- shopelectro/tests/tests_selenium_mobile.py
> #832 Fix mobile driver capabilities

- requirements.txt
- templates/catalog/catalog.html
- templates/catalog/category.html
- templates/catalog/product.html
- templates/pages/breadcrumbs.html
- templates/pages/breadcrumbs_with_siblings.html
> #838  Fix breadcrumbs microdata urls

- front/js/components/order.es6
- templates/ecommerce/order/table_form.html
> #846 Remove validation of privacy police checkbox

- templates/pages/breadcrumbs_with_siblings.html
> #844 Fix breadcrumbs markup

- front/js/components/admin.es6
- shopelectro/tests/tests_selenium_admin.py
> #858 Add in_pack field to table editor

- front/js/components/headerCart.es6
- front/js/components/successOrder.es6
- front/js/shared/tracking.es6
- gulpfile.babel.js
- shopelectro/tests/tests_selenium.py
- templates/ecommerce/order/success.html
> #853 Fix cart state after order

- shopelectro/management/commands/_update_catalog/update_pack.py
- shopelectro/models.py
- shopelectro/tests/tests_commands.py
> #859 Update prices depending on in_pack values 

- requirements.txt
- shopelectro/context_processors.py
- shopelectro/tests/tests_selenium_mobile.py
- shopelectro/tests/tests_views.py
- templates/catalog/catalog.html
- templates/catalog/category.html
- templates/catalog/product.html
- templates/layout/base.html
- templates/layout/metadata.html
> #850  Use absolute urls at the canonicals

- front/less/pages/catalog.less
- shopelectro/views/catalog.py
- templates/catalog/catalog.html
> #843  Fix matrix columns

- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_mobile.py
- shopelectro/views/catalog.py
- templates/catalog/category_products.html
- templates/pages/breadcrumbs.html
- templates/pages/breadcrumbs_with_siblings.html
Closes #837
Closes #855 
Closes #871
> #837,855,871  Doc matrix, crumbs delimeter, name hint

- docker/docker-compose.yml
> #838  Downgrade selenium to prevent chromedriver error

- shopelectro/management/commands/_update_catalog/update_pack.py
- shopelectro/tests/tests_commands.py
> #883  Fix catalog_update command

- front/js/shared/helpers.es6
- front/less/pages/product.less
- shopelectro/settings/local.py.dist
- shopelectro/views/catalog.py
- templates/layout/tile_products.html
- templates/layout/toggle_content.html
> #888,889  Minor remarkup product page

- front/less/common/variables.less
- front/less/pages/contacts.less
- templates/pages/page.html
Closes #890 
Preserved contacts page's code here: https://github.com/fidals/shopelectro/issues/890#issuecomment-505121906
> #890  Styles for the new contacts page

- shopelectro/management/commands/_update_catalog/update_pack.py
- shopelectro/models.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_commands.py
> #864 update pack

- shopelectro/context_processors.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_selenium_mobile.py
- templates/layout/google_tag_manager.html
> #881 fix mobile cart test

- shopelectro/admin.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_views.py
- templates/catalog/category_products.html
- templates/catalog/product.html
- templates/ecommerce/header_cart.html
> #866 render products in pack

- shopelectro/management/commands/price.py
- shopelectro/models.py
- shopelectro/settings/base.py
- shopelectro/tests/tests_commands.py
> #910  Fix excluding products from price

- .drone.yml
- requirements.txt
Closes https://github.com/fidals/stroyprombeton/issues/505
> stb#505 Rerun failed tests

- shopelectro/models.py
> #914 Document Product.vendor_code field

- front/less/pages/contacts.less
> #902  Remarckup mobile contacts page

- shopelectro/management/commands/_update_catalog/update_pack.py
- shopelectro/tests/tests_commands.py
> #927  Get rid of pack prices multiplication

- front/js/components/main.es6
- front/less/pages/main.less
- front/less/styles.less
- shopelectro/settings/base.py
- shopelectro/tests/tests_selenium.py
- shopelectro/tests/tests_selenium_mobile.py
- templates/layout/mobile_cart.html
> #903  Create slider for mobile version

- front/js/components/main.es6
- front/js/shared/configs.es6
- shopelectro/tests/tests_selenium.py
> #931 #932 Reinint info slider on resize. Move SCREEN to config

- front/js/shared/helpers.es6
- front/less/common/inputs.less
- front/less/pages/order.less
- front/less/pages/product.less
- templates/catalog/category_products.html
- templates/ecommerce/order/table_form.html
- templates/index/index.html
- templates/layout/back_call_modal.html
- templates/layout/toggle_content.html
> #952  Minor markup fixes from 12.09

- shopelectro/tests/tests_views.py
> #952  Test category root crumb siblings

- shopelectro/settings/base.py
- templates/layout/header.html
> #819  Rm "Возврат" link from the header

- shopelectro/tests/tests_views.py
- shopelectro/urls.py
- templates/500.html
> #758  Add custom 500 error page

- docker/Makefile
- docker/do-i18n.sh
> #942  Wait user approval to compile already made messages

- shopelectro/logic/__init__.py
- shopelectro/logic/header.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_logic.py
> #974  Sort the header menu

- shopelectro/logic/header.py
- shopelectro/settings/base.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_logic.py
- shopelectro/tests/tests_views.py
> #980  Refactor Header menu logic

- shopelectro/logic/header.py
- shopelectro/templatetags/se_extras.py
- shopelectro/tests/tests_logic.py
- shopelectro/tests/tests_views.py
- templates/layout/footer.html
- templates/layout/header.html
> #986  First leveled children

- shopelectro/logic/header.py
- shopelectro/management/commands/images.py
- shopelectro/tests/tests_views.py
> #990  Refresh images script

- shopelectro/management/commands/images.py
> #fix  Run images command in case of existing images

- .0pdd.yml
- Rm filename from tasks title
- Suppress not important mentions about existing tasks
> Fix pdd bot config

- front/less/common/variables.less
- front/less/pages/category.less
> #1000  Fix Buy button markup

- shopelectro/management/commands/price.py
- shopelectro/tests/tests_commands.py
- templates/prices/price.rss
- templates/prices/price.yml
> #1004  RSS price for Google Merchant

- .coafile
- shopelectro/settings/drone.py
- shopelectro/tests/tests_views.py
> #991  Fix stuck header menu tests

- shopelectro/tests/tests_views.py
- shopelectro/views/search.py
Products with no categories
Closes #1003
> #1003  Exclude orphan products from search

- shopelectro/management/commands/_update_catalog/update_tags.py
> Fix 1C import error
